name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run cargo fmt
      run: cargo fmt -- --check

    - name: Run cargo clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test
